export const mockData = {
  products: [
    {
      id: "1",
      name: "Monocrystalline Solar Panel",
      model: "SM-400W",
      wattage: "400W",
      price: 250,
      quantity: 150,
      image: "/monocrystalline-solar-panel.jpg",
      category: "Panel",
    },
    {
      id: "2",
      name: "Hybrid Solar Inverter",
      model: "HI-5000",
      wattage: "5000W",
      price: 1200,
      quantity: 45,
      image: "/solar-inverter.jpg",
      category: "Inverter",
    },
    {
      id: "3",
      name: "Lithium Solar Battery",
      model: "LB-10K",
      wattage: "10kWh",
      price: 3500,
      quantity: 30,
      image: "/solar-battery.png",
      category: "Battery",
    },
    {
      id: "4",
      name: "MPPT Charge Controller",
      model: "CC-100A",
      wattage: "100A",
      price: 450,
      quantity: 80,
      image: "/charge-controller.jpg",
      category: "Charge Controller",
    },
  ],

  stockRequests: [
    {
      id: "1",
      productName: "Monocrystalline Solar Panel",
      model: "SM-400W",
      quantity: 50,
      adminName: "Admin User",
      status: "pending" as const,
      requestedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      rejectionReason: undefined,
    },
    {
      id: "2",
      productName: "Hybrid Solar Inverter",
      model: "HI-5000",
      quantity: 20,
      adminName: "Admin User",
      status: "approved" as const,
      requestedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      rejectionReason: undefined,
    },
    {
      id: "3",
      productName: "MPPT Charge Controller",
      model: "CC-100A",
      quantity: 30,
      adminName: "Admin User",
      status: "rejected" as const,
      requestedDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      rejectionReason: "Insufficient stock available",
    },
  ],

  sales: [
    {
      id: "1",
      type: "B2B" as const,
      customerName: "GreenEnergy Corp",
      productName: "Monocrystalline Solar Panel",
      quantity: 100,
      totalAmount: 25000,
      paymentStatus: "completed" as const,
      saleDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      image: "/solar-panel-installation.png",
    },
    {
      id: "2",
      type: "B2C" as const,
      customerName: "John Smith",
      productName: "Hybrid Solar Inverter",
      quantity: 1,
      totalAmount: 1200,
      paymentStatus: "pending" as const,
      saleDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      image: "/solar-inverter.jpg",
    },
    {
      id: "3",
      type: "B2B" as const,
      customerName: "Solar Solutions LLC",
      productName: "Lithium Solar Battery",
      quantity: 15,
      totalAmount: 52500,
      paymentStatus: "completed" as const,
      saleDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      image: "/solar-battery.png",
    },
  ],
}
